# Generated by Django 5.0.1 on 2024-01-24 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospital",
            name="bank_account",
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="hospital_name",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="location",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="phone_number",
            field=models.PositiveBigIntegerField(),
        ),
        migrations.CreateModel(
            name="HospitalEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.hospital",
                    ),
                ),
                (
                    "name",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SystemEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.PositiveBigIntegerField()),
                (
                    "employee_name",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
