# Generated by Django 5.0.1 on 2024-01-28 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_alter_hospital_bank_account_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=256)),
                ("middle_name", models.CharField(max_length=256)),
                ("last_name", models.CharField(max_length=256)),
                ("phone_number", models.PositiveBigIntegerField()),
                ("age", models.PositiveSmallIntegerField()),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnose", models.CharField(max_length=256)),
                ("is_successful", models.BooleanField(default=False)),
                ("cost", models.PositiveIntegerField()),
                (
                    "case_type",
                    models.CharField(
                        choices=[("U", "Urgent"), ("S", "Surgery"), ("T", "Treatment")],
                        max_length=1,
                    ),
                ),
                (
                    "patient_name",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.hospital",
                    ),
                ),
            ],
        ),
    ]
