# Generated by Django 5.0.1 on 2024-02-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0003_alter_patientcase_case_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="sex",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")], max_length=6
            ),
        ),
    ]
