# Generated by Django 5.0.1 on 2024-02-04 09:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0004_alter_patient_sex"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientcase",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
