# Generated by Django 5.0.1 on 2024-02-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0005_patientcase_created_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientcase",
            name="is_approve",
            field=models.BooleanField(default=False),
        ),
    ]
