# Generated by Django 5.0.1 on 2024-02-14 20:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0006_patientcase_is_approve"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patientcase",
            options={"permissions": (("can_approve_cases", "Set case as approved"),)},
        ),
    ]
