# Generated by Django 5.0.1 on 2024-02-14 21:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0007_alter_patientcase_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patientcase",
            options={
                "permissions": (
                    ("can_approve_cases", "Set case as approved"),
                    ("can_succeed_case", "Set case as successful"),
                )
            },
        ),
    ]
