# Generated by Django 5.0.1 on 2024-02-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0009_alter_patientcase_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="age",
            field=models.PositiveIntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone_number",
            field=models.PositiveIntegerField(max_length=9),
        ),
    ]
