# Generated by Django 5.0.1 on 2024-02-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0011_alter_patient_age_alter_patient_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientcase",
            name="docs",
            field=models.FileField(null=True, upload_to="patients_docs"),
        ),
    ]
