# Generated by Django 5.0.1 on 2024-02-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0012_patientcase_docs"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientcase",
            name="is_accepted",
            field=models.BooleanField(default=False),
        ),
    ]
